import { Metadata } from "next";
import "./globals.css";
import NavBar from "./Components/NavBar";
import Footer from "./Components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>
          {`
            @import url('https://fonts.googleapis.com/css2?family=Helvetica&display=swap');

            body {
              font-family: 'Helvetica', sans-serif;
            }
          `}
        </style>
      </head>
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
